FROM golang:1.14.2-alpine3.11
# git is needed for go get. gcc and musl-dev are needed for go-sqlite3 (cgo)
RUN apk --no-cache add git gcc musl-dev \
  && go get github.com/cespare/reflex

COPY reflex.conf /

# App sources, Database, TLS cert and key
VOLUME ["/app", "/app/database/file", "/app/secrets"]

WORKDIR /app

EXPOSE 8443

# Watch for changes, rebuild and rerun the server
ENTRYPOINT ["reflex", "-c", "/reflex.conf"]
