FROM golang:1.14.5-alpine3.11
# git is needed for go get. gcc and musl-dev are needed for go-sqlite3 (cgo)
RUN apk --no-cache add git gcc musl-dev \
  && go get github.com/cespare/reflex

COPY reflex.conf /

# App sources volume, database volume, TLS cert and key volume, music volume
VOLUME ["/app", "/app/database/file", "/app/secrets" , "/music"]

WORKDIR /app

EXPOSE 8443

# Watch for changes, rebuild and rerun the server
ENTRYPOINT ["reflex", "-c", "/reflex.conf"]
