name: CI pipeline
on:
  push:
    branches-ignore: [ master ]
jobs:
  backend_tests:
    name: Test Go server
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out the code
      uses: actions/checkout@v2.3.2

    # Install dependencies

    - name: Go dependencies
      run: make dep

    # Build and test Go code

    - name: Build
      run: make build-ci

    - name: Go test coverage
      run: make coverage-go

    - name: Test race conditions
      run: make race

  backend_lint:
    name: Lint Go server
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2.3.2

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.0.0
        with:
          version: v1.30
          args: --enable goimports

  frontend_tests:
    name: Test Front-end
    runs-on: ubuntu-latest
    steps:

    - name: Check out the code
      uses: actions/checkout@v2.3.2

    # Install dependencies

    - name: NPM dependencies
      run: make npm-dep

    # Run Jest tests

    - name: Jest test coverage
      run: make coverage-jest

    # Static analysis and conformity to coding style

    - name: eslint
      run: make eslint-ci

    - name: Stylelint
      run: make stylelint-ci

    - name: Prettier for HTML and Javascript config
      run: make prettier-ci

  docker_image:
    name: Test Docker image
    runs-on: ubuntu-latest
    steps:

    - name: Install goss and dgoss
      uses: e1himself/goss-installation-action@v1
      with:
        # Goss release version to install
        version: 'v0.3.13'

    - name: Check out the code
      uses: actions/checkout@v2.3.2

    - name: Build the Docker image
      run: make build-docker-image

    - name: Run goss tests
      run: make dgoss-ci
