name: CI pipeline

on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and test Go code
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2.1.0

    - name: Get dependencies
      run: go mod download

    - name: Build
      run: go build -v .

    - name: Test with coverage
      run: go test -v -covermode=count -coverprofile=count.out ./...

    - name: Test race conditions
      run: go test -race -v ./...

    # Publish coverage to the build log
    - name: Publish coverage
      run: go tool cover -func=count.out

  style:
    name: Coding style conformity and static analysis
    runs-on: ubuntu-latest
    steps:
      - name: Go lint
        uses: Jerome1337/golint-action@v1.0.1

      # test -z returns code 1 when its argument is not empty. gofmt -l returns the files that are not well-formatted
      - name: Go format
        run: test -z $(gofmt -l .)

      - name: Go vet
        run: go vet -v ./...

      - name: Stylelint
        run: npm run stylelint ./assets

      - name: Prettier for HTML
        run: npm run prettier -- --list-different ./templates
