name: CI pipeline
on:
  push:
    branches-ignore: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Install goss and dgoss
      uses: e1himself/goss-installation-action@v1
      with:
        # Goss release version to install
        version: 'v0.3.10'

    - name: Check out the code into the Go module directory
      uses: actions/checkout@v2.1.0

    # Install dependencies

    - name: Go dependencies
      run: make dep

    - name: NPM dependencies
      run: make npm-dep

    # Build and test Go code

    - name: Build
      run: make build

    - name: Test coverage
      run: make coverhtml

    - name: Test race conditions
      run: make race

    # Static analysis and conformity to coding style

    - name: Go lint
      uses: Jerome1337/golint-action@v1.0.1

    - name: Go format
      run: make goformat

    - name: Stylelint
      run: make stylelint-ci

    - name: Prettier for HTML
      run: make prettier-ci

    # Build and test the docker image

    - name: Build the Docker image
      run: make build-docker-image

    - name: Run goss tests
      run: make dgoss-ci
