name: Docker Hub publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          # Goss release version to install
          version: 'v0.3.10'
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag hyzual/mike-sierra-sierra:latest
      - name: Run goss tests
        run: dgoss run hyzual/mike-sierra-sierra:latest
      - name: Push the Docker image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hyzual/mike-sierra-sierra
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
