name: Docker Hub publish
on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Install goss and dgoss
        uses: e1himself/goss-installation-action@v1
        with:
          # Goss release version to install
          version: 'v0.3.11'

      - name: Check out the code
        uses: actions/checkout@v2.1.0

      - name: Build the Docker image
        run: make build-docker-image

      - name: Run goss tests
        run: make dgoss-ci

      - name: Push the Docker image to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: hyzual/mike-sierra-sierra
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
